/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutUsTW: typeof import('./src/components/AboutUsTW.vue')['default']
    AidenComponents: typeof import('./src/components/AidenComponents.vue')['default']
    AsciiCar: typeof import('./src/components/AsciiCar.vue')['default']
    AsciiCar2: typeof import('./src/components/AsciiCar2.vue')['default']
    BuildLegoMath: typeof import('./src/components/BuildLegoMath.vue')['default']
    ChatArea: typeof import('./src/components/ChatArea.vue')['default']
    ChatAreaTW: typeof import('./src/components/ChatAreaTW.vue')['default']
    ChatResult: typeof import('./src/components/ChatResult.vue')['default']
    ChatWithGemini: typeof import('./src/components/ChatWithGemini.vue')['default']
    CTATemplateTW: typeof import('./src/components/CTATemplateTW.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    FeatureSectionInPanelTW: typeof import('./src/components/FeatureSectionInPanelTW.vue')['default']
    FeatureSectionTW: typeof import('./src/components/FeatureSectionTW.vue')['default']
    HeroAppScreenshotTW: typeof import('./src/components/HeroAppScreenshotTW.vue')['default']
    HeroSectionTW: typeof import('./src/components/HeroSectionTW.vue')['default']
    HeroWithBackgroundImageTW: typeof import('./src/components/HeroWithBackgroundImageTW.vue')['default']
    HeroWithImageTW: typeof import('./src/components/HeroWithImageTW.vue')['default']
    LandingPageFooter: typeof import('./src/components/LandingPageFooter.vue')['default']
    LongDivision: typeof import('./src/components/LongDivision.vue')['default']
    LongMultipicationMath: typeof import('./src/components/LongMultipicationMath.vue')['default']
    PricingSectionTW: typeof import('./src/components/PricingSectionTW.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInAndRegistrationTW: typeof import('./src/components/SignInAndRegistrationTW.vue')['default']
    StatsWithImageTW: typeof import('./src/components/StatsWithImageTW.vue')['default']
    WavyHeroTW: typeof import('./src/components/WavyHeroTW.vue')['default']
  }
}
